# Generated by Django 2.1.2 on 2018-10-19 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('rate_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=10)),
                ('writer_id', models.CharField(max_length=10)),
                ('delivery_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('account', models.CharField(default='Check', max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(default='0', max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
    ]
