# Generated by Django 2.1 on 2018-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('account', models.CharField(default='Check', max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
    ]
