# Generated by Django 2.1 on 2018-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181015_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='1', max_length=10, primary_key=True, serialize=False),
        ),
    ]
