# Generated by Django 2.1 on 2018-10-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181022_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='courier',
            fields=[
                ('courier_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('account', models.CharField(default='Check', max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('company_id', models.CharField(default='0', max_length=10)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
    ]
