# Generated by Django 2.1 on 2018-10-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20181022_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='career',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='courier',
            name='phone',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='courier',
            name='age',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.CharField(default='1', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='gender',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='courier',
            name='password',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='1', max_length=10, primary_key=True, serialize=False),
        ),
    ]
