# Generated by Django 2.1 on 2018-10-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('track_id', models.CharField(max_length=20)),
                ('r_address', models.CharField(max_length=50)),
                ('s_address', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('r_phone', models.CharField(max_length=20)),
                ('s_phone', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('s_postcode', models.CharField(max_length=20)),
                ('r_postcode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('box_id', models.CharField(max_length=20)),
                ('company_id', models.CharField(max_length=20)),
                ('delivery_staff', models.CharField(max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
