# Generated by Django 2.1.2 on 2018-10-19 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
