# Generated by Django 2.1 on 2018-10-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181014_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
