# Generated by Django 2.1 on 2018-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20181014_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default='0', max_length=10, primary_key=True, serialize=False),
        ),
    ]
