# Generated by Django 2.1 on 2018-10-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20181014_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False),
        ),
    ]
