# Generated by Django 2.1 on 2018-10-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20181019_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='r_address',
            new_name='receiver_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='r_phone',
            new_name='receiver_phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='s_address',
            new_name='send_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='s_phone',
            new_name='send_phone',
        ),
    ]
