# Generated by Django 2.1 on 2018-10-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20181019_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default='1', max_length=10, primary_key=True, serialize=False),
        ),
    ]
