# Generated by Django 2.1 on 2018-10-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20181021_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1', max_length=10, primary_key=True, serialize=False),
        ),
    ]
