# Generated by Django 2.1 on 2018-10-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.CharField(default='1', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='0', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
